[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/anacrolix/missinggo"

[[constraint]]
  branch = "master"
  name = "github.com/anacrolix/torrent"

[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "2.0.6"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/bosh-utils"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/jlaffaye/ftp"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "4.0.5"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
